### ISSUE TITLE
Spring Boot文档中有一段漏了翻译 https://springdoc.cn/spring-boot/howto.html#howto.nosql

### ISSUE THREAD

**Issue by dokcn** [spring-doc/feedback#1]
![C2F12593-C82A-47EC-8517-A66E20858828](https://user-images.githubusercontent.com/24841978/228872000-8e55f5e0-d8c5-4297-a821-db13d664985d.png)

**Comment by KevinBlandy** [comment]
谢谢，已修复，下个版本发布更新。
