### ISSUE TITLE
spring-core-1.8.1. 使用 BeanPostProcessor 自定义 Bean

### ISSUE THREAD

**Issue by wurara** [spring-doc/feedback#10]
这里的【使用 [用】 是否有重复？

https://springdoc.cn/spring/core.html#beans-factory-extension-bpp

要改变实际的Bean定义（即定义Bean的蓝图），你需要使用 BeanFactoryPostProcessor，如 使用 [用 BeanFactoryPostProcessor 定制配置元数据](https://springdoc.cn/spring/core.html#beans-factory-extension-factory-postprocessors) 中所述。

**Comment by KevinBlandy** [comment]
是的，重复了。已经修改了，下次一起更新！谢谢！
