### ISSUE TITLE
spring-core-2.8.2. Application Context 构造器资源路径中的通配符

### ISSUE THREAD

**Issue by wurara** [spring-doc/feedback#13]
这句“因为一个资源一次只指向一个资源。”中的第一个资源是不是应该不翻译。第一个资源应该是Resources对象，一个Resources对象一次只指向一个资源。

https://springdoc.cn/spring/core.html#resources-app-ctx-wildcards-in-resource-paths
原文
请注意，这种通配符是专门针对在application context构造器中使用资源路径的（或者当你直接使用 PathMatcher 实用类层次结构时），并在构造时解析。它与 Resource 类型本身没有关系。你不能使用 classpath*: 前缀来构造一个实际的 Resource，因为一个资源一次只指向一个资源。

**Comment by KevinBlandy** [comment]
是的，这一句翻译欠妥。已经修改为：一个 `Resources` 对象一次只指向一个资源。

谢谢！
