### ISSUE TITLE
《数据访问》中5.3.3标题“生命式事务分界”，应该是“声明式”吧？

### ISSUE THREAD

**Issue by breezefaith** [spring-doc/feedback#17]
![image](https://github.com/spring-doc/feedback/assets/20924601/61f14576-fd56-42ca-beba-b843e623127e)

**Comment by KevinBlandy** [comment]
是的，这里翻译错了。

**Comment by breezefaith** [comment]
已收到您的来信，非常感谢

**Comment by KevinBlandy** [comment]
已处理，谢谢。
