### ISSUE TITLE
Spring Data文档中有一段中英文并存 而且中文翻译有误(豆名) https://springdoc.cn/spring-data/#repositories.configuration

### ISSUE THREAD

**Issue by dokcn** [spring-doc/feedback#2]
![820BF5AF-0518-4C73-8090-B56004482738](https://user-images.githubusercontent.com/24841978/228873813-46a2b3e2-d43d-4bc8-ac47-ad3a3942403b.jpeg)

**Comment by KevinBlandy** [comment]
已经修复，下个版本会更新。谢谢！
