### ISSUE TITLE
https://springdoc.cn/spring/core.html#core.aot 本节的AOT指AOT编译(提前编译) 不应只翻译为提前

### ISSUE THREAD

**Issue by dokcn** [spring-doc/feedback#4]
![Snipaste_2023-04-08_22-35-53](https://user-images.githubusercontent.com/24841978/230727163-ac68d578-15bd-4b18-b018-e10f57628a4d.png)

还有https://springdoc.cn/spring/testing.html#testcontext-aot
![Snipaste_2023-04-08_22-37-26](https://user-images.githubusercontent.com/24841978/230727185-96045cbd-4aea-4967-8ed0-1acb625462ba.png)

**Comment by KevinBlandy** [comment]
已修复，谢谢。
