### ISSUE TITLE
https://springdoc.cn/spring/data-access.html#tx-prog-template   绝对能让你与Spring的事务基础设施和API结合起来

### ISSUE THREAD

**Issue by hugh-zhan9** [spring-doc/feedback#5]
![1681184425772](https://user-images.githubusercontent.com/49809663/231050294-0c37a9ab-5874-4a98-8765-31547a980e9a.png)

翻译成以下这样：

>就像你马上要在后面的例子中看到的那样， 使用 TransactionTemplate 绝对会增加你的代码与Spring的事务框架和API间的耦合。 到底编程式事务管理是不是适合你的项目需要由你自己来决定。

是否会更好

**Comment by KevinBlandy** [comment]
谢谢提出意见，参考你以及ChatGPT的翻译，做了如下修改：

> 正如下面的示例所示，使用 TransactionTemplate 会将你与Spring的事务基础设施和API绝对地耦合在一起。是否适合使用编程式事务管理是你需要自己决定的，这取决于你的开发需求。
