### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by lightingtime** [spring-doc/feedback#7]
https://springdoc.cn/spring/core.html#beans-factory-class-instance-factory-method
里
![image](https://user-images.githubusercontent.com/13469581/233535066-522136a2-bf18-424b-a73f-670e7d6d4d76.png)
'"工厂（Factory）Bean" 是指在Spring容器中配置的Bean...'  这一句，原文写的是 '"factory bean" refers to a bean that is configured in the Spring container...'， 可见 '"工厂(Factory)" Bean...' 应改为 '"工厂(factory)" bean'

**Comment by KevinBlandy** [comment]
已修复，谢谢。
