### ISSUE TITLE
spriong-core-1.7. Bean 定义（Definition）的继承

### ISSUE THREAD

**Issue by wurara** [spring-doc/feedback#9]
这里的C hildBeanDefinition，没有把C包括进去。

https://springdoc.cn/spring/core.html#beans-child-bean-definitions

如果你以编程方式处理 ApplicationContext 接口，子bean定义由C `hildBeanDefinition` 类表示。大多数用户不会在这个层面上与他
们一起工作。相反，他们在 ClassPathXmlApplicationContext 这样的类中声明性地配置Bean定义。当你使用基于XML的配置元数据
时，你可以通过使用 parent 属性来指示子Bean定义，将父Bean指定为这个属性的值。下面的例子显示了如何做到这一点。

**Comment by KevinBlandy** [comment]
已修复，下次统一更新。谢谢！
